name: Run Python tests

on: [push]

jobs:
  python-tests:
    name: Run tests (setup-python)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install pytest pytest-md pytest-emoji
      - uses: ./.
  
  python-quoting:
    name: Test quoting
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install pytest pytest-md pytest-emoji
      - uses: ./.
        with:
          custom-arguments: -k "not failed"

  micromamba-tests:
    name: Run tests (setup-micromamba)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Conda env
        uses: mamba-org/setup-micromamba@db1df3ba9e07ea86f759e98b575c002747e9e757
        with:
          environment-name: myenv
          cache-environment: true
          create-args: >-
            python
            pytest
            pytest-md
            pytest-emoji
      - uses: ./.
