name: Run Python tests

on: [push]

jobs:
  python-tests:
    name: Run tests (setup-python)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: szenius/set-timezone@dd47655c84241eec2ffa0a855959c16c0920c3c4
        with:
          timezoneLinux: 'Europe/Berlin'
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install pytest pytest-md pytest-emoji
      - uses: Quantco/pytest-action@v2

  micromamba-tests:
    name: Run tests (provision-with-micromamba)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: szenius/set-timezone@dd47655c84241eec2ffa0a855959c16c0920c3c4
        with:
          timezoneLinux: 'Europe/Berlin'
      - name: Set up Conda env
        uses: mamba-org/provision-with-micromamba@a319a818023c3a5a448a60bd72e0c633408fbccc
        with:
          environment-name: myenv
          channels: conda-forge
          environment-file: false
          extra-specs: |
            python
            pytest
            pytest-md
            pytest-emoji
      - uses: Quantco/pytest-action@v2
